version: '3.8'

services:
  test-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uber-eats-test-api
    environment:
      - DATABASE_URL=postgresql://test_user:test_pass@test-postgres:5432/test_db
      - REDIS_URL=redis://test-redis:6379/0
      - ENVIRONMENT=testing
      - UBER_EATS_CLIENT_ID=test_client_id
      - UBER_EATS_CLIENT_SECRET=test_client_secret
      - UBER_EATS_WEBHOOK_SECRET=test_webhook_secret
      - UBER_EATS_SANDBOX_MODE=true
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
    depends_on:
      - test-postgres
      - test-redis
    networks:
      - test-network
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        echo 'Running tests...' &&
        pytest tests/ -v --cov=app --cov-report=term-missing --cov-report=html
      "

  test-postgres:
    image: postgres:16-alpine
    container_name: uber-eats-test-postgres
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=test_db
    networks:
      - test-network

  test-redis:
    image: redis:7-alpine
    container_name: uber-eats-test-redis
    networks:
      - test-network

networks:
  test-network:
    driver: bridge