# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-uber-eats"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PROJECT_NAME = "Uber Eats API"
  VERSION = "1.0.0"
  API_V1_STR = "/api/v1"
  ENVIRONMENT = "production"
  DEBUG = "false"
  LOG_LEVEL = "INFO"
  UBER_EATS_SANDBOX_MODE = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[services]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    port = 8000
    timeout = "10s"
    type = "http"

[metrics]
  port = 8000
  path = "/metrics"